name: Keep Supabase Awake

on:
  schedule:
    - cron: '0 0 * * 0,4'
  workflow_dispatch: 
jobs:
  ping_db:
    runs-on: ubuntu-latest
    steps:
      - name: Send Wakeup Call to Supabase
        run: |
          curl -i -X POST "https://dedytnfmdjtfabqxkjcv.supabase.co/rest/v1/snippets" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Prefer: resolution=merge-duplicates" \
          -d '{"tunnus": "KEEP_ALIVE_PING", "code_text": "print(\"stayin alive\")"}'
